language: cpp
sudo: false

# List of apt packages available from Travis CI
# can be found at: https://github.com/travis-ci/apt-package-whitelist
addons_shortcuts:
  addons_clang35: &clang35
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.5']
      packages: ['clang-3.5', 'g++-4.9', 'cmake', 'cmake-data', 'nodejs', 'npm']
  addons_clang38: &clang38
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.8']
      packages: ['clang-3.8', 'g++-4.9', 'cmake', 'cmake-data', 'nodejs', 'npm']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      packages: ['g++-4.9', 'cmake', 'cmake-data', 'nodejs', 'npm']
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      packages: ['g++-6', 'cmake', 'cmake-data', 'nodejs', 'npm']

matrix:
  include:
    # Debian 8 Jessie, default setup: clang-3.5, g++-4.9
    - os: linux
      compiler: clang
      env: COMPILER_VERSION=3.5
      addons: *clang35
    - os: linux
      compiler: gcc
      env: COMPILER_VERSION=4.9
      addons: *gcc49
    # Other versions
    - os: linux
      compiler: clang
      env: COMPILER_VERSION=3.8
      addons: *clang38
    - os: linux
      compiler: gcc
      env: COMPILER_VERSION=6
      addons: *gcc6

script:
  - export CC="${CC}-${COMPILER_VERSION}"
  - export CXX="${CXX}-${COMPILER_VERSION}"
  - export CXX_STD="c++14"
  - cmake .
  - make -j4
  - chmod +x check_compatibility.sh
  - ./check_compatibility.sh
  - chmod +x check_output.sh
  - time ./check_output.sh -n 5  # number_repr is the base case
  - time ./check_output.sh -c 5  # char_repr @ case # 1 -- from number_repr
  - time ./check_output.sh -c f  # char_repr @ case # 2 -- from undefined
  - time ./check_output.sh -c a  # char_repr @ case # 3 -- from NaN
  - time ./check_output.sh -c +  # char_repr @ case # 4 -- from 1e+308
  - time ./check_output.sh -c c  # char_repr @ case # 5 -- from function
  - time ./check_output.sh -c r  # char_repr @ case # 6 -- from true
  - time ./check_output.sh -c s  # char_repr @ case # 7 -- from false
  - time ./check_output.sh -c B  # char_repr @ case # 8 -- from constructor name
  - time ./check_output.sh -c z  # char_repr @ case # 9 -- from a-z
  - time ./check_output.sh -c C  # char_repr @ case #10 -- from atob("20N")
  - time ./check_output.sh -c Z  # char_repr @ case #11 -- from fromCharCode
  - time ./check_output.sh -t "Hello"
