language: cpp
sudo: false

# List of apt packages available from Travis CI
# can be found at: https://github.com/travis-ci/apt-package-whitelist
addons_shortcuts:
  addons_clang35: &clang35
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.5']
      packages: ['clang-3.5', 'g++-4.9', 'cmake', 'cmake-data']
  addons_clang38: &clang38
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.8']
      packages: ['clang-3.8', 'g++-4.9', 'cmake', 'cmake-data']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      packages: ['g++-4.9', 'cmake', 'cmake-data']
  addons_gcc6: &gcc6
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      packages: ['g++-6', 'cmake', 'cmake-data']

matrix:
  include:
    # Debian 8 Jessie, default setup: clang-3.5, g++-4.9
    - os: linux
      compiler: clang
      env: COMPILER_VERSION=3.5
      addons: *clang35
    - os: linux
      compiler: gcc
      env: COMPILER_VERSION=4.9
      addons: *gcc49
    # Other versions
    - os: linux
      compiler: clang
      env: COMPILER_VERSION=3.8
      addons: *clang38
    - os: linux
      compiler: gcc
      env: COMPILER_VERSION=6
      addons: *gcc6

script:
  - export CC="${CC}-${COMPILER_VERSION}"
  - export CXX="${CXX}-${COMPILER_VERSION}"
  - export CXX_STD="c++14"
  - cmake .
  - make -j4
  - ./build/js6chars -n 5  # number_repr is the base case
  - ./build/js6chars -c 5  # char_repr @ case # 1 -- from number_repr
  - ./build/js6chars -c f  # char_repr @ case # 2 -- from undefined
  - ./build/js6chars -c a  # char_repr @ case # 3 -- from NaN
  - ./build/js6chars -c +  # char_repr @ case # 4 -- from 1e+308
  - ./build/js6chars -c c  # char_repr @ case # 5 -- from function
  - ./build/js6chars -c r  # char_repr @ case # 6 -- from true
  - ./build/js6chars -c s  # char_repr @ case # 7 -- from false
  - ./build/js6chars -c B  # char_repr @ case # 8 -- from constructor name
  - ./build/js6chars -c z  # char_repr @ case # 9 -- from a-z
  - ./build/js6chars -c C  # char_repr @ case #10 -- from atob("20N")
  - ./build/js6chars -c Z  # char_repr @ case #11 -- from fromCharCode
  - ./build/js6chars -s "Hello"
